#!/usr/bin/env python3
"""
Weekly domain report script for TryBooking UK.
Extracts email domains from user data and sends CSV report to marketing/data team.
"""
import os
import pandas as pd
from datetime import datetime

# Import shared modules
from modules.utils.config import TEST_MODE, UK_TZ

# Check if email sending is enabled
SEND_EMAILS = os.environ.get("SEND_EMAILS", "true").lower() == "true"
from modules.utils.data_loader import load_users
from modules.utils.date_utils import get_week_dates, get_latest_data_date
from modules.utils.email_utils import send_html_email_with_attachments
from modules.utils.validation import validate_environment_variables
from modules.utils.performance import timer_decorator


@timer_decorator
def extract_email_domains(df):
    """Extract email domains from Username column."""
    # Ensure Username column exists (column 4 as per requirement)
    if 'Username' not in df.columns:
        # Try to use the 4th column (0-indexed would be column 3)
        if len(df.columns) > 3:
            username_col = df.columns[3]
            df['Username'] = df[username_col]
        else:
            raise ValueError("Username column not found in data")
    
    # Extract domain from email addresses (everything after @)
    df['EmailDomain'] = df['Username'].str.split('@').str[-1]
    
    # Filter out rows without valid domains (no @ symbol would result in the full username)
    df = df[df['Username'].str.contains('@', na=False)]
    
    # Get unique domains and their counts
    domain_counts = df['EmailDomain'].value_counts().reset_index()
    domain_counts.columns = ['Domain', 'Count']
    
    # Sort by count (descending) then alphabetically
    domain_counts = domain_counts.sort_values(['Count', 'Domain'], ascending=[False, True])
    
    return domain_counts


@timer_decorator
def generate_domain_report():
    """Generate weekly domain report from user data."""
    print("Starting weekly domain report generation...")
    
    try:
        # Load the latest user data
        target_date = get_latest_data_date()
        print(f"Loading user data for {target_date}...")
        
        users_df = load_users(target_date)
        print(f"Loaded {len(users_df)} user records")
        
        # Extract email domains
        domain_report = extract_email_domains(users_df)
        print(f"Extracted {len(domain_report)} unique domains")
        
        # Generate report dates for email subject
        week_start, week_end = get_week_dates()
        
        
        # Prepare email
        subject = f"Weekly Email Domain Report - {week_start.strftime('%d %b')} to {week_end.strftime('%d %b %Y')}"
        
        # Create HTML body with summary statistics
        top_domains = domain_report.head(10)
        total_domains = len(domain_report)
        total_users = domain_report['Count'].sum()
        
        html_body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2>Weekly Email Domain Report</h2>
            <p>Report generated on {datetime.now(UK_TZ).strftime('%d %B %Y at %H:%M')} UK time</p>
            
            <h3>Summary Statistics</h3>
            <ul>
                <li><strong>Total unique domains:</strong> {total_domains:,}</li>
                <li><strong>Total users:</strong> {total_users:,}</li>
                <li><strong>Data date:</strong> {target_date.strftime('%d %B %Y')}</li>
            </ul>
            
            <h3>Top 10 Domains</h3>
            <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse;">
                <thead>
                    <tr style="background-color: #f2f2f2;">
                        <th>Domain</th>
                        <th>User Count</th>
                        <th>Percentage</th>
                    </tr>
                </thead>
                <tbody>
        """
        
        for _, row in top_domains.iterrows():
            percentage = (row['Count'] / total_users) * 100
            html_body += f"""
                    <tr>
                        <td>{row['Domain']}</td>
                        <td style="text-align: right;">{row['Count']:,}</td>
                        <td style="text-align: right;">{percentage:.1f}%</td>
                    </tr>
            """
        
        html_body += """
                </tbody>
            </table>
            
            <p style="margin-top: 20px;">
                <em>The complete list of all domains is attached as a CSV file.</em>
            </p>
            
            <p style="color: #666; font-size: 12px; margin-top: 30px;">
                This is an automated report generated by the TryBooking UK reporting system.
            </p>
        </body>
        </html>
        """
        
        # Determine recipients based on TEST_MODE
        if TEST_MODE:
            recipients = ["alex@trybooking.co.uk"]
            print("TEST MODE: Sending to test recipients only")
        else:
            # Marketing/data team recipients
            recipients = [
                "louise@trybooking.co.uk",  # Update with actual marketing team email
            ]
        
        # Save CSV to temporary file for attachment
        temp_csv_path = f'/tmp/email_domains_{target_date.strftime("%Y%m%d")}.csv'
        domain_report.to_csv(temp_csv_path, index=False)
        
        # Send email if enabled
        if SEND_EMAILS:
            send_html_email_with_attachments(
                to=recipients,
                subject=subject,
                html_content=html_body,
                attachments=[temp_csv_path]
            )
            print(f"Report sent successfully to {', '.join(recipients)}")
        else:
            print("Email sending disabled - report generated but not sent")
        
        # Also save locally for debugging if needed
        if TEST_MODE:
            local_filename = f'email_domains_{target_date.strftime("%Y%m%d")}.csv'
            domain_report.to_csv(local_filename, index=False)
            print(f"Report also saved locally as {local_filename}")
        
        return domain_report
        
    except Exception as e:
        print(f"Error generating domain report: {e}")
        raise


def main():
    """Main entry point."""
    # Validate required environment variables
    required_vars = [
        'AWS_ACCESS_KEY_ID',
        'AWS_SECRET_ACCESS_KEY',
        'MAILGUN_SMTP_LOGIN',
        'MAILGUN_SMTP_PASSWORD'
    ]
    
    validate_environment_variables(required_vars)
    
    # Generate and send the report
    generate_domain_report()
    
    print("Weekly domain report completed successfully")


if __name__ == "__main__":
    main()